### ISSUE TITLE
question about filling scoring matrix

### ISSUE THREAD

**Issue by Chiyasa** [labstructbioinf/pLM-BLAST#45]
Thank you for this excellent work! I have a question about filling the scoring matrix after reading the article and source code: in https://github.com/labstructbioinf/pLM-BLAST/blob/886a8fbee3b66c76141ed0580444caf25176e5b9/alntools/numeric.py#L131, pLM-BLAST local used the maximum value from 1 to i+1 as the candidate filling value, not as in pLM-BLAST global or traditional SW algorithm, which just use i as the candidate. What is the purpose of this design?

**Comment by Chiyasa** [comment]
another question is that, in the article it claimed that "...the above equation does not truncate the values to zero", however, both i+1 in the https://github.com/labstructbioinf/pLM-BLAST/blob/886a8fbee3b66c76141ed0580444caf25176e5b9/alntools/numeric.py#L131, j+1 in the https://github.com/labstructbioinf/pLM-BLAST/blob/886a8fbee3b66c76141ed0580444caf25176e5b9/alntools/numeric.py#L133, and line https://github.com/labstructbioinf/pLM-BLAST/blob/886a8fbee3b66c76141ed0580444caf25176e5b9/alntools/numeric.py#L123 will cause the value to be truncated to zero. Did I missunderstand something？

**Comment by Argusmocny** [comment]
Hi, thanks for intresting questions. 
1. The global mode is more like NW approach, local uses SW-like filling, where off diagonal elements `h_tmp[1]` and `h_tmp[2]` are selected by scanning row/column values. We use python `range` function so (1, i+1) becomes (1, i).
2. Thanks for pointing this, you are correct, later we discovered that values below zero are very rare and only slightly negative (probably as a consequence of network activation functions). And if they appear in one point, all neighboring points are ~0 or negative. This is because substitution matrix of p5 is "smooth" - values are gradually changing. Hence paths derived from scoring matrix are omiting low similarity regions, when we do clip them to 0, they are omited anyway. At the beginning we believed that negative values will act similar to gap penalty.  Anyway I will change this back to match publication text :)

**Comment by Chiyasa** [comment]
Thanks for your explanation!

**Comment by Chiyasa** [comment]
Thanks for your explanation! I will close this issue.
