### ISSUE TITLE
[QUESTION] what is the "score" reported by pLM-BLAST? 

### ISSUE THREAD

**Issue by DaRinker** [labstructbioinf/pLM-BLAST#57]
Apologies if I have missed something (I've been through the paper and the documentation couple of times) but I can't find a description of how the plmblast score is calculated, or how it should be interpreted. It looks to have a range of 0-1 scale but I'm not sure how to think about evaluating (or thresholding) that number. Is 

Asking because I now have hundreds of results and want to intelligently summarize them. I have cases where I have single short hits, and cases with multiple short hits to the same target. Each hit has a score <0.5 (sometimes <<) but my inclination is to take the multi-hit targets as more likely (than the single hits) to be distant homologs to my query.  Am I thinking about this correctly?
 
Thank you

**Comment by DaRinker** [comment]
Just circling back to this. 

I double checked the paper (and the documentation) and still cannot find how this score is calculated or how one might think about thresholding it. The MPI server simply calls this an "alignment score", but I cannot find that term used anywhere else...?

**Comment by Argusmocny** [comment]
@DaRinker Hi
You are right we should emphasize it more. The `score` is simply average cosine similarity per alignment - in other words we take cosine similarity of each pair in the final alignment (gaps also) and calculate its mean. In general it may take values from -1 to 1 but due to embeddings value distribution (propably due to the acitvation functions) is more likely (0-1)

**Comment by DaRinker** [comment]
Ahhhhh!! Thank you for clarifying. So, this the same cosine similarity that the pre-filtering step is acting on as well?

And judging by Fig2B (and what you just said here), I should evaluate a score of 0.5 based upon an expected score interval of [0,1] (not  [-1,1])?

**Comment by Argusmocny** [comment]
@DaRinker 

>  So, this the same cosine similarity that the pre-filtering step is acting on as well?

No it different. In pre-filtering we use so-called chunk cosine similarity which is coarse-grained search. In which we compare regions not individial residues typically 30 residues regions. This allow us check whether a sequene pair posess **any simillar region** if so we move on to the reqular plmblast algorithm to extract is location (alignment) and fitness measure (score).

> And judging by Fig2B (and what you just said here), I should evaluate a score of 0.5 based upon an expected score interval of [0,1] (not [-1,1])?

No because the distribution of the per residue cosine similarities is not symmetric it has skewness. It looks similar to https://en.wikipedia.org/wiki/Skewness#/media/File:Relationship_between_mean_and_median_under_different_skewness.png (positive skew). In our research we found that meaningful alignments appear above ~0.25. 


PS. If you have any other questions or suggestion how to make the documentation better feel free to share them :)

**Comment by DaRinker** [comment]
Excellent. Thank you for clarifying this. Very helpful.

In my case, I'm getting several hits with scores in the .40-.45 range. Sounds like I should be considering these as likely, remote homologs. 

And as for the documentation, I think having some practical examples/guidelines for evaluating the output of pLM-BLAST would be immensely helpful.

Thanks again for your help!

**Comment by DaRinker** [comment]
I'm going to reopen this ticket because I have a related, follow-on question related to the reasonable interpretation of the scores.

In short, I've finally completed an extensive analysis of over 500,000 proteins using pLM BLAST and am now writing up the results. I am now grappling with how I should best present/interpret the results. 

Quick summary of my question and strategy: the question I'm interrogating with pLM-BLAST is whether any of a given set of Species have an likey ortholog to a query gene of interest. The test Species set was previously characterized as being species that failed to return any hits having a seq-ID >33% using a conventional protein BLAST.

When I query this GOI using pLM-BLAST on this proteins in my target Species, I repeatedly get multiple hits (~ 6 hits per species). These hits generally have pLM scores in the range of (0.3-0.35). Because we don't expect any (or most) species to have multiple copies of these genes, I'm not sure how to interpret multiple hits that have similar scores? Are they all likely candidates, or does their common set of scores make them less likely to be candidate?

To help contextualize these results further, I also created a "reference" proteome from ~70 sister species that are expected to have an ortholog to this gene (again, based on protein BLAST). Again, pLM BLAST returns multiple hits for each query (lots again in the .3-.4 range) and then maybe one "standout" hit (score >0.5) that corresponds to the true ortholog.

So I am inclined to say that pLM BLAST is telling me that most of by test Species are lacking any concrete evidence of an ortholog (in spite of scores in the low .3-s). Would you agree with this? Or should I be more aggressive in my interpretation?
